### ISSUE TITLE
Suggestion regardin instructions! 

### ISSUE THREAD

**Issue by Moros1138** [henrywalters/olc-2024-the-runner#1]
If you'd like people to be able to, easily, build this from source I suggest you  this to your instructions so people realize that they need to install the imgui submodule and have a means to do it easily at clone time!

```
git clone --recurse-submodules https://github.com/henrywalters/olc-2024-the-runner
```

**Comment by henrywalters** [comment]
Thanks a lot! It has been done

**Comment by Moros1138** [comment]
you seem to have built this on linux and i'm struggling...


i got that engine built (had to add some includes, pr incoming), and the cmake finds it fine but i keep getting thing that are missing in the engine... like

```
In file included from /home/jon/Projects/CodeJam2024/olc-2024-the-runner/src/game.cpp:19:
In file included from /home/jon/Projects/CodeJam2024/olc-2024-the-runner/src/scenes/runtime.h:11:
In file included from /home/jon/Projects/CodeJam2024/olc-2024-the-runner/src/scenes/../common/mapBuilder.h:10:
/home/jon/Projects/CodeJam2024/olc-2024-the-runner/src/scenes/../common/tiles.h:27:68: error: no member named 'yellow' in 'hg::graphics::Color'
   27 |     TileDef {TileType::Sand, hg::Vec2i(1, 0), hg::graphics::Color::yellow()},
      |                                               ~~~~~~~~~~~~~~~~~~~~~^
/home/jon/Projects/CodeJam2024/olc-2024-the-runner/src/scenes/../common/tiles.h:30:65: error: no member named 'magenta' in 'hg::graphics::Color'
   30 |     TileDef{TileType::Ice, hg::Vec2i(0,2), hg::graphics::Color::magenta()},
      |                                            ~~~~~~~~~~~~~~~~~~~~~^
2 errors generated.
```

and it's correct in [HaGameLite repo](https://github.com/henrywalters/HaGameLite/blob/main/include/hagame/graphics/color.h#L72), it is indeed missing these colors. I'm guessing you have a local copy of the repo and forgot about the changes you made to it?

**Comment by henrywalters** [comment]
You are absolutely correct!! Thanks for catching that! I've just pushed the latest engine code updates. Thanks again
